# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='architectural_needs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='data_entry',
        ),
        migrations.RemoveField(
            model_name='project',
            name='executive_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='preliminary_study',
        ),
    ]
